name: Android CI

on:
  push:
  release:
    types:
      - created
      - edited

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: init git submodules
      run:  git submodule init && git submodule update && ls
    - name: copy tunnelblick patches
      run: cp -r /home/runner/work/ics-openvpn-xor/ics-openvpn-xor/tunnelblick-patches/* /home/runner/work/ics-openvpn-xor/ics-openvpn-xor/main/src/main/cpp/openvpn
    - name: apply patches
      run: cd /home/runner/work/ics-openvpn-xor/ics-openvpn-xor/main/src/main/cpp/openvpn && git apply 02-tunnelblick-openvpn_xorpatch-a.diff && git apply 03-tunnelblick-openvpn_xorpatch-b.diff && git apply 04-tunnelblick-openvpn_xorpatch-c.diff && git apply 05-tunnelblick-openvpn_xorpatch-d.diff && git apply 06-tunnelblick-openvpn_xorpatch-e.diff
    - name: delete patch files
      run: find . -name "*.diff" -type f -delete
    - name: Android build action
      uses: xdtianyu/actions-android-ci@master
      with:
        args: '"apt-get update && apt-get -y install swig && ./setup-android-sdk.sh && ./setup-android-ndk.sh && ./gradlew assembleDebug"'
    - name: Upload artifact - dump outputs folder
      uses: actions/upload-artifact@v1.0.0
      with:
        name: gradle outputs folder
        path: /home/runner/work/ics-openvpn-xor/ics-openvpn-xor/main/build/outputs
